### PR TITLE
Release workflow

### PR DESCRIPTION
**Pull request by erinn**
There is a lot here so I'll try to go through this thoroughly because some of it I can't test only you can.

The workflow should work, I've got a very similar one working on a project of my own. However, I can't execute actions on your repo, only you can. This action is only triggered on a tag, so the way to make this happen is to use bumpver in the master branch after you have merged this PR: `bumpver update --patch` this should, if everything works right, bump the version numbers in the respective files, git tag the version number, and push the tag to GitHub at which point the release workflow will be triggered. 

The workflow is fairly simple, on windows get the right version of python, install requirements and requirements-dev and then build binaries using pytinstaller. After that innosetup takes over and creates the installer itself. I've run the resultant through virustotal, hopefully this is visible: https://www.virustotal.com/gui/file/bfb297c5ff544cd4f2bc09df0f4181acacf6735bfc835ea7cb0a2c0fd491072d/detection

Nothing detected. 

So at the end of this you will have a releases section on GitHub with four files total, a zip of the binaries, a setup exe and then a zip and tar gz of the entire repo. 

The setup program itself can't be set to install system wide because radiolog currently writes files to the installed location. This should probably be fixed in the future, best practice is to keep all writes out of the install location, but that's for another day. Right now the installer is restricted to install as the current user which means the install ends up in the AppData folder. 

IF all of this works, we are literally down to picking icons for the install, right now it is some default duck/disk thing (shrug). But it gets you closer to a good installer. Icons will need to be configured for pyinstaller and for innosetup. But I believe that is fairly simple. 

Give it a good look and let me know. Test out the resultant install heavily. I'll be out for the entire week backpacking. Will get back to you next weekend if needed. 

This should be fairly close to fixing #29 and then #467 would need some attention to update the doc with the new options.

### CODE REVIEW

**Comment by caver456** [comment]
Looks like great progress!  I have a couple of questions before merging, when you get back from your trip:

- looks like none of the changed files in this PR actually affect the functional code, so there's no hesitation there - but
- sounds like the PR must first be merged in order to test the PR?
- If the way to test it out is to first merge the PR and then run bumpver, would that mean that the new version would be at least 3.0.1?  Not sure it matters much, but should we maybe make the current version 2.9.9 so that we can bumpver as a test to 2.9.10 and then maybe do the icons and such and bumpver to 3.0.0?
- I'm out backpacking starting next Saturday July 30, getting back mid-August, then probably out and offline intermittently for another few weeks.
- We had a good mock search on July 9, which resulted in several new issues on this repo.  None of them are red-alert priority.  Is it best to wait until after this PR is merged to tackle the various new issues?  That would certainly take the time pressure off as well.

**Comment by erinn** [comment]
Yes and no on it first needs to be merged. To do 'releases', well I'm not sure really, but you probably don't want to create tags in branches. Tags are probably only useful to be on main/master. This HAS been tested by me, here: https://github.com/erinn/kconsole (it's basically a toy project right now where I am working out what is needed for radiolog) the workflow is close, but not exactly the same because I am also releasing for Linux. So it is reasonably tested, but yes for this, it's a bit of a chicken and egg issue.

Personally, I don't worry about the version number so much, most people don't care anymore except to say that 'X is newer than Y which is what I have installed so I should upgrade'. But it's your call, and because there are no 3.x.x tags in place you could certainly do this. But like I said, I'd just try 3.0.1, if that breaks, 3.0.2 etc. until the workflow works. 

As you mentioned this doesn't touch any real code, so you should be able to do whatever work you wish there without creating any conflicts.

**Comment by caver456** [comment]
Makes sense, sounds like it's best to just push forward.  Good point with the versioning, 3.0.0 it is.  Merging...

**Comment by caver456** [comment]
Didn't make time to try it out during the week.  We're headed out for 2-6 weeks starting tomorrow, so this is a bit rushed, sorry bout that.  No doubt I'm missing something simple cause I am not a git guru, but:

(.radiolog.venv) PS C:\Users\caver\Documents\GitHub\.radiolog.venv\radiolog-master (6)\radiolog-master> bumpver update --patch
INFO    - Old Version: 3.0.0
INFO    - New Version: 3.0.1
WARNING - Version Control System not found, skipping commit.
(.radiolog.venv) PS C:\Users\caver\Documents\GitHub\.radiolog.venv\radiolog-master (6)\radiolog-master>

(this is after doing the pip install -r requirements.txt and pip install -r requirements-dev.txt in a fresh venv, both of which seemed to work just fine)

**Comment by erinn** [comment]
Ah, ok so what bumpver is trying to do is do a git tag operation on the main/master branch. HOWEVER, you don't appear to have git installed or have git in your path. I have a vague memory that you use github desktop or something? So if my memory is correct, your steps would be something like this, run bumpver to bump the version numbers in all the right location on master. Move over to github desktop, commit the changes and then tag them: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags once the tag is pushed to master in Github the release workflow will kick off and package the application for you. We can write that up in the documentation too, but I don't use Github Desktop so I'll leave it to you to work through it (let me know if you need any help).

**Comment by caver456** [comment]
Just got back from 18 days hiking today - sorry bout the long delay.  We
head out again in a few days for a road trip without computer, but I do
plan to make time between now and then to give this a shot.  I do use
github desktop, but it creates a full clone including the .git directory.
Sounds like I want to run from there, instead of from a fresh venv which
doesn't have the .git directory.  Makes complete sense of course - I was
trying things too hastily before we left town for the trip.

**Comment by erinn** [comment]
Let me know what help you need. Also found this, you may find it interesting: https://github.com/addisonElliott/pyqt5ac in addition you should be aware (if you ever want to move to QT6) that pyqt6 doesn't support compiling qrc files anymore, pyside6 does still. Not suggesting anything, just passing along hard won knowledge from today :).

**Comment by caver456** [comment]
Tried doing the same from a new powershell terminal in the actual clone dir which does have a .git subdir, but still no go.  So, it's probably not just looking for a .git subdir - it's probably actually looking for git in the path - that's probably what you said but of course all of this would be easier if I was just running linux instead.  Terminology gets a bit intercotwangulated when hopping between linux and windows as you know.

So - I got further by launching a powershell from within github desktop - this apparently includes git in the command line:
image

Then, in that powershell:

```
PS C:\Users\caver\Documents\GitHub\radiolog> bumpver update --patch
INFO    - fetching tags from remote (to turn off use: -n / --no-fetch)
INFO    - Old Version: 3.0.0
INFO    - New Version: 3.0.1
ERROR   - Error running subcommand: ['git', 'add', '--update', '.githubworkflowsrelease.yml']
fatal: pathspec '.githubworkflowsrelease.yml' did not match any files
PS C:\Users\caver\Documents\GitHub\radiolog>
```

That filename looks like it just removed the slashes from the valid filename.  On a hunch, I changed bumpver.toml to use double-slashes in the pathname, which should work in both windows and linux:

".github\\workflows\\release.yml" = [
    "version: '{version}'"
]

Trying bumpver again it gives this warning:

```
PS C:\Users\caver\Documents\GitHub\radiolog> bumpver update --patch
INFO    - fetching tags from remote (to turn off use: -n / --no-fetch)
INFO    - Old Version: 3.0.0
INFO    - New Version: 3.0.1
WARNING - git working directory is not clean. Uncomitted file(s):
WARNING -     M bumpver.toml
PS C:\Users\caver\Documents\GitHub\radiolog>
```

So, I did a manual commit (in github desktop) of bumpver.toml, then tried again - evidently that didn't fix it - do you know where that pathname is getting deslashed?

```
PS C:\Users\caver\Documents\GitHub\radiolog> bumpver update --patch
INFO    - fetching tags from remote (to turn off use: -n / --no-fetch)
INFO    - Old Version: 3.0.0
INFO    - New Version: 3.0.1
ERROR   - Error running subcommand: ['git', 'add', '--update', '.githubworkflowsrelease.yml']
fatal: pathspec '.githubworkflowsrelease.yml' did not match any files
PS C:\Users\caver\Documents\GitHub\radiolog>
```

**Comment by erinn** [comment]
Ah windows, never making life easy… Ok well bumpver needs to be fixed to work with multiple platforms. That’s not really your issue to tackle at the moment, so let’s just have you manually do what bumpver is doing. 

So if you look in bumpver.toml you’ll see all the files it searches to update the version information. If you manually change those to say 3.0.1 and then commit your change, you can then tag a release ‘3.0.1’ and push that tag to GitHub. At that point a build will be triggered by GitHub actions and it should create your installer. 

So let’s validate that first and see if it is working. Bumpver on windows may not be all that useful given the path separator issue. I’ll have a look and see if I can fix their code, the pathlib module should be useful for this. 

Anyway, if you’re willing do the manual steps, skip bumpver altogether for the moment and let’s see if we can get an installer built automatically.

**Comment by caver456** [comment]
Thanks for being patient.  Bumpver did change the version number in the
files, including in .github/workflows/release.yml, so that's still handy.
Looks like it's only getting deslashed in the git call.  So, I committed
and pushed the four changed files - only the version number strings changed
in those file, as expected - then I made a tag in github desktop on that
recent commit and then pushed that tag from github desktop.  The new tag
3.0.1 does show up online.  It does look like the action worked, on the
releases 3.0.1. page I see radiolog-setup.exe and
radiolog-windows-3.0.1.exe (what's the difference between those files?) -
so that's success, right?  I will try radiolog-windows-3.0.1.exe in a fresh
venv.

**Comment by caver456** [comment]
drrr, zip vs exe.  I read it too fast.

Anyway I downloaded and ran the .exe, didn't try to do a venv cause that
wouldn't really jive in this case - but it installed to the appdata dir and
seems to work!  Amazing! Will try to break it in the next day or so before
we leave town again, but, this looks like a huge win.

**Comment by caver456** [comment]
Looks good so far, though I haven't tried to exercise much of the
functionality.  I've asked a few of our radiolog operators to install the
program and test it out.

A few questions about the new setup:

- if we need to do a hotfix in the field / during an operation, is there a
good way to accomplish this?  It's only been done a small handful of times,
but, it involved hacking on radiolog.py directly and then restarting and
restoring the previous data.

- the radiolog/local dir should probably be bubbled up higher, maybe to the
same as the first working dir, which should probably be changed from
~/Documents to something like ~/Documents/radiolog, then there could be
~/Documents/radiolog/local (with radiolog.cfg and the logo) and
~/Documents/radiolog/NewIncident-blahblah.csv etc.  Anyway I think you
already mentioned that the whole concept of where things get stored should
be reworked - that should probably also include radiolog.rc and
radiolog_blahblah.log.

- In the past we've found it handy to have the .log show up in a terminal
so we could just take a photo of a traceback or such as it happens, using a
smartphone.  That method of bug reporting has actually been very helpful
over time.  But, it is extra clutter to have the terminal window open, and
it can sometimes be confusing to the operator, who might close the terminal
inadvertently.  (Not all radiolog operators are techies, and they shouldn't
have to be techies, so these things happen/ed.)  Anyway - maybe an
alternative to having the log file be visible in the terminal, is to have
it also copied to the second working directory which, in our case, is a
shared network drive on our trailer LAN.  That way, anyone on any computer
on the LAN could view the radiolog log file in real time if needed.  [The
main purpose of the second working dir is so that other tools that read the
radiolog data in real time can have access to it, like the plans_console
repo which is gaining favor vs the radiolog_viewer repo.]

**Comment by erinn** [comment]
I don't believe there is a good way to do a hotfix other than pulling down the source and fixing there. I don't know all the details of what pyinstaller does, but I believe it compiles everything up and tries to package it in as close to binary form as is possible. There may be some funky way to unpack it all and reverse it, but like I said simplest is probably a clone from the tag, and make your fix there and run on. 

Yes your 'write' locations need to change as does the locations where you store your settings so that it is not blown away every time an upgrade happens. QSetinngs probably makes the most sense for holding setting in a platform agnostic way, [pyqtconfig](https://www.pythonguis.com/code/pyqtconfig/) may be worth a look too (I haven't used it yet). qsettings works fine, but it has no concept of type, everything is stored as a string, you can specify type when retrieving values, like int etc. but pyqtconfig 'solves' that type problem, I guess.

Storing your data needs to go somewhere else. Certainly 'Documents/something' is reasonable, I suppose it depends on the data. User data that is needed should probably go there, internal data, like logs... well probably elsewhere is better. But both of these should go through [QStandardPaths](https://doc.qt.io/qt-6.2/qstandardpaths.html) my opinion obviously. This will allow the 'right' paths to be accessed in a platform agnostic way. So you want DocumentsLocation and AppLocalDataLocation I'd guess. I can probably help with that here shortly.

Your console, yeah consoles are handy, but also confusing. I'd say an optional console would be ideal. I dunno how to code it up, but you've seen it before, click a button the console appears with all the logs in it. Just my thought. Your other option is to package the program up so that the console is always displayed. Either way, but I prefer the former. I'm tackling something similar myself so when I work though it in my program I can probably come back with a reasonable console option.

**Comment by caver456** [comment]
This is definitely a lot of good stuff and all those suggestions sound
great - more than I can keep up with, at least for now, but that is not a
problem.  We head out in the morning for another week and a half or so.
Will be at email intermittently, and if any of our radiolog users that are
trying the install discover any issues I'll pass them along to you.

**Comment by caver456** [comment]
Here's a checklist of things to try on a new release to build confidence before installing in the command vehicles.  This list may just be a temporary and redundant crutch, only used for the first few installations of new versions; or it may become the standardized qualification checklist for any new release.  Either way - so be it:

Without fleetsync (all from keyboard):

| keyboard | fleetsync | item
|------------|------------|----------|
|<ul><li>- [ ] </li></ul>|<ul><li>- [ ] </li></ul>| new entries from keyboard - at least two callsigns
|- [ ] | - [ ] | set status based on message text or quick text - check team tab color and STATUS columns
|- [ ] | - [ ] | add a clue
|- [ ] | - [ ] | increment OP

**Comment by caver456** [comment]
Just to be clear, this list is something I should have done a few months back when @erinn first rolled out the release workflow in this PR.  Example: #536.  Better late than never.

**Pull request merged**
