### PR TITLE
Move icons to separate location

### PR DESCRIPTION
**Pull request by erinn**
As a small step in the prep work for having an installer it makes it much easier to have the icons (binary blobs really) located in a single location. 

I've moved the icons into the icons/ folder and updated the corresponding .ui files (as well as regenerating the resultant .py files) as well as the qrc files and regeneration of the resultant rc files. 

I tested this lightly on my system, icons appear as I believe they should, but clearly would love some more testing by folks who have used this extensively.

### CODE REVIEW

**Comment by caver456** [comment]
Nice - would you expect that just opening all the various dialogs, to make
sure all the various icons show up, would be sufficient testing?

**Comment by caver456** [comment]
Also - in another repo, I finally bit the bullet and made the code to automatically regenerate the _ui.py and _rc.py files at runtime.  Would this be the right time to incorporate those?  Seems like maybe that should be spun out to a different module to be included with various repos?  Or maybe someone else has already done the same thing but better?

From plans_console.py in the ncssar/plans_console repo:

```
# rebuild all _ui.py files from .ui files in the same directory as this script as needed
#   NOTE - this will overwrite any edits in _ui.py files
for ui in glob.glob(os.path.join(os.path.dirname(os.path.realpath(__file__)),'*.ui')):
    uipy=ui.replace('.ui','_ui.py')
    if not (os.path.isfile(uipy) and os.path.getmtime(uipy) > os.path.getmtime(ui)):
        cmd='pyuic5 -o '+uipy+' '+ui
        logging.info('Building GUI file from '+os.path.basename(ui)+':')
        logging.info('  '+cmd)
        os.system(cmd)

# rebuild all _rc.py files from .qrc files in the same directory as this script as needed
#   NOTE - this will overwrite any edits in _rc.py files
for qrc in glob.glob(os.path.join(os.path.dirname(os.path.realpath(__file__)),'*.qrc')):
    rcpy=qrc.replace('.qrc','_rc.py')
    if not (os.path.isfile(rcpy) and os.path.getmtime(rcpy) > os.path.getmtime(qrc)):
        cmd='pyrcc5 -o '+rcpy+' '+qrc
        logging.info('Building Qt Resource file from '+os.path.basename(qrc)+':')
        logging.info('  '+cmd)
        os.system(cmd)
```

**Comment by erinn** [comment]
So even with the move it looks like all icons are held in qrc files, meaning as long as the qrc files are regenerated with the icons pulled in it doesn’t really matter that they are in a new subdir. However, yes that is all the testing I did, click about make sure the icons appear as expected. 

 

As for regenerating the qrc files and the ui files automatically I’d personally advise looking into GitHub Actions. This is the route I’ll be using to create the installer (FYI using pyinstaller already have a binary generated). You can take a look at the work I’ll do on that soonish. Basic idea is this, on new tag to master binary installer is generated and placed on the releases page. No human intervention is needed. For regeneration of the qrc and ui files I’d do something along the same lines. On some sort of trigger, merge into master/main pull request, something, or even just a timer, every week, regenerate ui and qrc files. The one issue you may run into is without a test suite you can guarantee that whatever you are putting out there works. So ultimate good solution is regenerate files, run test suite, if pass, commit code. But that is further down the road and may or may not be worth the time.

**Comment by caver456** [comment]
Makes sense - two concerns though:
- on the ui and qrc regeneration on-the-fly, the reason I coded that in
there was because I got tired of rebuilding by hand every time during
development.  I would rebuild 100 times before doing a commit, then rebuild
another few dozen times for each new commit involving GUI changes.
Certainly there's no harm in doing it as a github action as well, if I
understand, but, if we include the code so that rebuild happens at runtime,
then the github action might not be necessary?  Let me know if I'm
understanding that correctly.
- I tried pyinstaller a lot in the ncssar/gpsio repo, and ultimately came
to the conclusion that it is a dead ducky because the generated executable
always gets flagged as a virus threat by some number of antivirus tools,
including the one that Windows comes with.  That repo mentions the website
you can upload your executable to in order to check how many antivirus
tools flag it as a threat.  Anyway after all that exploration I went for
NSIS with the python embeddable plus whatever modules are needed by
requirements.txt.  Have you had experiences navigating the pyinstaller
virus threat flag thing?

**Comment by erinn** [comment]
Fair enough. It certainly helps to build tooling for development work. So roll with that. If needed actions can be used later. 

No experience with the virus scanner. I assumed that at some point code signing would be necessary and I think that’ll help? Windows isn’t really my world. But I’ll explore and get back to you. 

Any which way, when your good with this PR please merge it (or let me know why not).

**Comment by caver456** [comment]
Sounds good - FYI here's the gpsio issue in question:
https://github.com/ncssar/gpsio/issues/24

As far as incorporating the rebuild-at-runtime code, do you think it's best
to roll it in to this PR, or to do it separately after merging this one?

**Comment by erinn** [comment]
Separate.

**Pull request merged**
