### PR TITLE
Move QT designer files into subdir and ui files into module. 

### PR DESCRIPTION
**Pull request by erinn**
So this is an opinion, you can take it or leave it as you see, it's your project after all. 

I moved all the QT designer files into the designer subdir, and the resultant ui files that are generated into the ui subdir/module. This cleans up your base considerably and should not effect functionality. Basically this is all cosmetic, but it makes things better organized in my opinion. 

All the imports were also updated in the process as well as removing a number of unused imports (PyCharm did this automatically) and I removed the min mode code that appears to have no ui file associated with it anymore.

Finally during the course of this move I noticed two generated ui files are unused:
convertDialog_ui.py 
subjectLocated_ui.py 

I moved them over just to be thorough in case there is something I am not understanding. But as I said looks like those are unused. It also looks like in the case of convertDialog there is a lot of commented out code referencing that around line 6177. Perhaps that should be removed?

### CODE REVIEW

**Comment by caver456** [comment]
Just got back from the road a couple days ago.  Thanks for digging in to this.  There's a lot of code that's not up to any real standards for sure.  I'm definitely a fan of cleanup, especially if it reduces pain and makes things more usable for other contributors, though I'm a bit conflicted about doing big cleanup without a bunch of automated testing in place, which would be a huge task to get good coverage.  To mitigate the heebegeebies I'd like to take a little time to look through the changes and exercise the various bits.  Looks pretty straightforward.  Will take that on this evening.

**Comment by erinn** [comment]
Yeah the actual code change is minimal. This is more just a move files around to make things a bit clearer (to me at least, you may think differently :). 

Give it some thought, no worries if it isn’t for you.

-Erinn

**Comment by caver456** [comment]
Based on looking at affected files, need to check these items (I'll do these checks now - sorry was delayed due to a callout and sleep)

- [ ] open and close all dialogs
  - [ ] help
  - [ ] options
  - [ ] fsSendDialog
  - [ ] fsSendMessageDialog
  - [ ] newEntryWindow
  - [ ] newEntryWidget
  - [ ] clueDialog
  - [ ] clueLogDialog
  - [ ] printDialog
  - [ ] changeCallsignDialog
  - [ ] fsFilterDiaog
  - [ ] opPeriodDialog
  - [ ] printClueLogDialog
  - [ ] nonRadioClueDialog
  - [ ] subjectLocatedDialog
- [ ] print
  - [ ] radio log
  - [ ] team radio logs
  - [ ] clue log
  - [ ] clue report

**Comment by caver456** [comment]
Noticed some issues while running thru the checklist - will see if they also exist in the master branch, and if so, will gladly merge the PR.  It's definitely a good thing to do cleanup where the testing is clear and easily achievable!

- print: all generated pdfs have a large top and bottom margins, as if they are generated with heights appropriate to landscape, but are being generated on portrait pages
- clue log - print button has no icon
- subject located - attributeerror on accept; probably related to a previous easy issue; if so, will commit separately after this PR

**Comment by caver456** [comment]
confirmed, these issues all exist in master.  Merging.

**Comment by caver456** [comment]
just to follow up:
- clue log print icon - opened and fixed as #489
- subjectLocationDialog exception - already-open misnamed issue #475 was updated, and fixed
- generated pdfs (except clue report) - not immediately clear - opened issue #490

**Pull request merged**
